{
        # hyperparams for training
        "classifier": {
                "architect_settings": {
                        "name": "classifier-test",
                        "backbone": {
                                "name": "swin-s",
                                "is_full": False,
                                "is_pretrained": True,
                                "is_freeze": False,
                        },
                        "n_cls": 10,
                        "is_caps": False,
                        "caps": {
                                "mode": 1,
                                "cap_dims": 4,
                                "routing": {
                                        "type": "dynamic",
                                        "params": [3, 0.1, 1.5]
                                        }
                                }
                        },
                "dataset_settings": {
                        "name": "CIFAR10",
                        "path": "data/",
                        "img_size": 224,
                        },
                "training_settings":{
                        "gpu_ids": [1],
                        "n_gpu": 1,
                        "loss": "ce",
                        "ckpt_path": "./mode/test",
                        "n_epoch": 50,
                        "n_batch": 64,
                        "num_workers": 12,
                        "optimizer": "adam",
                        "lr_scheduler": "step",
                        "lr": 0.0001,
                        "lr_step": 10,
                        "lr_decay": 0.8,
                        "momentum": 0.9,
                        "weight_decay": 0.005,
                }
        },
        
        "segment": {
                "architect_settings" : {
                        "name": "model-test",
                        "backbone": {
                                "name": "fcn-m",
                                "is_full": False,
                                "is_pretrained": True,
                                "is_freeze": False, 
                        },
                        "n_cls": 2,
                        "is_caps": True,
                        "caps": {
                                "mode": 1,
                                "cap_dims": 4,
                                "routing": {
                                        'type': "fuzzy",
                                        'params': [3, 0.01, 1.5]}
                                }
                        },
                "dataset_settings": {
                        "name": "LungCT-Scan",
                        "path": "data/CT-scan-dataset",
                        "img_size": 224,
                        },
                "training_settings":{
                        "gpu_ids": [0],
                        "n_gpu": 1,
                        "loss": "ce",
                        "ckpt_path": "./mode/test",
                        "n_epoch": 50,
                        "n_batch": 32,
                        "num_workers": 12,
                        "optimizer": "adam",
                        "lr_scheduler": "step",
                        "lr": 0.0001,
                        "lr_step": 10,
                        "lr_decay": 0.8,
                        "momentum": 0.9,
                        "weight_decay": 0.005,
                }
        },

        "detect": {
                "architect_settings" : {
                        "name": "model-test",
                        "backbone": {
                                "name": "fasterrcnn-m",
                                "is_full": False,
                                "is_pretrained": True,
                                "is_freeze": False, 
                        },
                        "n_cls": 2,
                        "is_caps": True,
                        "caps": {
                                "mode": 1,
                                "cap_dims": 4,
                                "routing": {
                                        'type': "dynamic",
                                        'params': [3, 0.01, 1.5]}
                                }
                        },
                "dataset_settings": {
                        "name": "PennFudan",
                        "path": "data/PennFudanPed",
                        "img_size": 320,
                        },
                "training_settings":{
                        "gpu_ids": [0],
                        "n_gpu": 1,
                        "loss": "none",
                        "ckpt_path": "./mode/test",
                        "n_epoch": 50,
                        "n_batch": 8,
                        "num_workers": 12,
                        "optimizer": "adam",
                        "lr_scheduler": "step",
                        "lr": 0.0001,
                        "lr_step": 10,
                        "lr_decay": 0.8,
                        "momentum": 0.9,
                        "weight_decay": 0.005,
                }
        }
}