{
        # hyperparams for training
        "classifier": {
                "task": "classification",
                "architect_settings": {
                        "name": "classifier-test",
                        "backbone": {
                                "name": "resnet-s",
                                "is_full": False,
                                "is_pretrained": True,
                                "is_freeze": False,
                        },
                        "n_cls": 10
                },
                "dataset_settings": {
                        "name": "CIFAR10",
                        "path": "data/",
                        "img_size": 224,
                        },
                "training_settings":{
                        "gpu_ids": [0],
                        "n_gpu": 1,
                        "loss": "ce",
                        "ckpt_path": "./mode/test",
                        "n_epoch": 5,
                        "n_batch": 64,
                        "num_workers": 0,
                        "optimizer": "adam",
                        "lr_scheduler": "step",
                        "early_stopping": True,
                        "lr": 0.0001,
                        "lr_step": 10,
                        "lr_decay": 0.8,
                        "momentum": 0.9,
                        "weight_decay": 0.005,
                }
        },
        
        "segment": {
                "task": "segmentation",
                "architect_settings" : {
                        "name": "model-test",
                        "backbone": {
                                "name": "deeplab-m",
                                "is_full": False,
                                "is_pretrained": True,
                                "is_freeze": False, 
                        },
                        "n_cls": 2
                },
                "dataset_settings": {
                        "name": "LungCT-Scan",
                        "path": "data/CT-scan-dataset",
                        "img_size": 224,
                        },
                "training_settings":{
                        "gpu_ids": [0],
                        "n_gpu": 1,
                        "loss": "ce",
                        "ckpt_path": "./mode/test",
                        "n_epoch": 100,
                        "n_batch": 16,
                        "num_workers": 0,
                        "optimizer": "adam",
                        "lr_scheduler": "step",
                        "early_stopping": False,
                        "lr": 0.0001,
                        "lr_step": 10,
                        "lr_decay": 0.8,
                        "momentum": 0.9,
                        "weight_decay": 0.005,
                }
        },

        "detect": {
                "task": "detection",
                "architect_settings" : {
                        "name": "model-test",
                        "backbone": {
                                "name": "fasterrcnn-m",
                                "is_full": False,
                                "is_pretrained": True,
                                "is_freeze": False, 
                        },
                        "n_cls": 2
                },
                "dataset_settings": {
                        "name": "PennFudan",
                        "path": "data/PennFudanPed",
                        "img_size": 320,
                        },
                "training_settings":{
                        "gpu_ids": [0],
                        "n_gpu": 1,
                        "loss": "none",
                        "ckpt_path": "./mode/test",
                        "n_epoch": 50,
                        "n_batch": 4,
                        "num_workers": 0,
                        "optimizer": "adam",
                        "lr_scheduler": "step",
                        "early_stopping": False,
                        "lr": 0.0001,
                        "lr_step": 10,
                        "lr_decay": 0.8,
                        "momentum": 0.9,
                        "weight_decay": 0.005,
                }
        }
}