name: pytorch
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.9
  - pip
  - pytorch-cuda=11.6
  - torchvision
  - pytorch
  - neptune
  - pip:
    - gradio
    - ipython
    - scikit-learn
    - scipy
    - numpy
    - opencv-python
    - pillow
    - matplotlib
    - torchmetrics
    - pytorch-lightning