name: pytorch
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - pip
  - pytorch-cuda=11.6
  - torchvision
  - torchmetrics
  - pytorch
  - pip:
    - numpy
    - scipy
    - scikit-learn
    - matplotlib
    - gradio
    - ipythons
    - opencv-python
    - pillow
    - pytorch-lightning
    - neptune